### PR TITLE
Version v0.6.9: SDK upgrade, Ledger Stax UI, Improve Blind Signing behavior

### PR DESCRIPTION
**Pull request by vldmkr**
### Features:
- [Nano S/SP/X] Always inform about the blind signing, even if the option is activated in the settings.
- [Nano S/SP/X] Invite users to enable the blind signing setting during the signature request.
- Upgrade to a newer version of the SDK
- Add MAX_TRANSACTION_PACKETS to Makefile for TARGET_STAX
- Implement the UI for Ledger Stax
  - Separate the common UI code for BAGL and NBGL
  - Put general functions into utils
  - Refactor BAGL UI (display, menu, settings)
  - Implement NBGL UI (display, menu, settings)
  - Add Aptos icon for Ledger Stax
- Expand the displayed info
  - Parse `0x1::aptos_account::transfer_coins` function
  - Now show "Transaction Type" for all entry_function calls
  - Add support for multisig payload variant
- Add new tests.
- Update workflows for misspellings checks, coding style checks, documentation generation, clang static analyzer, Python client checks, CodeQL checks, build and functional tests.
- Version bump to v0.6.9.

### Fixes:
- [v0.6.2] Fix typo on Blind Signing warning screen
- [v0.6.2] Fix the tests, remove the obsolete ones after an upgrade
- [v0.6.3] Use "no_throw" crypto functions instead of deprecated ones
- [v0.6.6] Rewrite existing tests using the Ragger framework.

## Changes include
* [x]  Bugfix (non-breaking change that solves an issue)
* [x]  New feature (non-breaking change that adds functionality)
* [ ]  Breaking change (change that is not backwards-compatible and/or changes current functionality)
* [x]  Tests
* [x]  Documentation
* [ ]  Other (for changes that might not fit in any category)

### CODE REVIEW

**Comment by junkil-park** [comment]
@vldmkr , These look like great improvements to the app. I am particularly interested in the multisig payload support. Can I know what the release timeline for Version v0.6.9 is?

**Comment by hardsetting** [comment]
Thanks for including my changes @vldmkr!
Is there anything I can help you with in order to get this merged, maybe a PR review?

**Comment by hardsetting** [comment]
I also have a small question, not necessarily related to this PR (although if it's quick and we can get it in, that'd be amazing).

What is the reasoning for requiring a message to be UTF-8 encoded?
https://github.com/LedgerHQ/app-aptos/blob/846999c63de8354e48cec96bfadf0e7005f38183/src/transaction/deserialize.c#L127-L131

We've gotten requests from people that were looking into doing key rotation, or other operations that involve signing a structured message (not UTF-8).

Removing this limitation would effectively unblock them.

**Comment by vldmkr** [comment]
> @vldmkr , These look like great improvements to the app. I am particularly interested in the multisig payload support. Can I know what the release timeline for Version v0.6.9 is?

@junkil-park  Thank you! At the moment the app source code is undergoing a security audit. I believe that once this iterative process is over, the Ledger team will accept the PR shortly. We are all eagerly awaiting this!

**Comment by hardsetting** [comment]
Thank you @vldmkr for the amazing run down.
I follow your input and implemented the change [here](https://github.com/pontem-network/ledger-app-aptos/pull/6).

Changes and tests are in separate commits, hopefully that helps the review.

**Review by tdejoigny-ledger — APPROVED** [review]

**Comment by tdejoigny-ledger** [comment]
Jira ticket : B2CA-1555

**Pull request merged**
